INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (8, '05 Duke Street', 'Portobelo', '527');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (44, '066 Raven Park', 'Samālūţ', '08');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (29, '1226 Nevada Way', 'Las Piñas', '6150');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (22, '1531 Crowley Junction', 'San Pedro Apartado', '82');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (19, '170 Corry Road', 'Dahu Satu', '394');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (9, '2 Karstens Lane', 'Mutum Biyu', '83');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (48, '21 Corben Terrace', 'Kawm Ḩamādah', '94');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (4, '3 American Drive', 'Rosebank', '986');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (33, '3 David Center', 'Lanxi', '12901');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (20, '32834 Farragut Pass', 'Joinville', '0');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (14, '35 Logan Crossing', 'Hefei', '4978');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (25, '4 Drewry Court', 'Kalamáta', '0');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (49, '4 Pine View Street', 'Tegalagung', '6113');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (43, '444 Bobwhite Lane', 'Bouna', '206');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (11, '4473 Kim Court', 'Velká Dobrá', '95321');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (7, '49 Forest Parkway', 'Manjing', '0');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (35, '49179 Merry Crossing', 'East End', '7');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (17, '5 Mcguire Junction', 'Komorniki', '2084');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (15, '5 Muir Terrace', 'Daegu', '717');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (38, '5 Northview Parkway', 'Kuching', '8');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (5, '5 Schiller Trail', 'Sarāvān', '95462');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (27, '52551 International Drive', 'Kawangkoan', '5335');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (28, '5259 Jay Crossing', 'Suicheng', '91725');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (3, '55 Hoffman Park', 'Fifi', '5');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (16, '55541 Sutteridge Way', 'Hongmiao', '0374');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (23, '5584 Bultman Lane', 'Cabay', '17091');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (45, '57 Waxwing Trail', 'Yinxi', '0155');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (26, '599 Delaware Pass', 'Rozhniv', '7');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (12, '6 Anthes Road', 'Xiabuji', '3');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (32, '6 Drewry Hill', 'Koronowo', '93');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (13, '66022 Meadow Ridge Street', 'Ansongo', '037');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (36, '69845 Browning Road', 'Kon Tum', '9');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (37, '71635 Harbort Point', 'Aragarças', '26');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (21, '75566 Bobwhite Road', 'Anchau', '86379');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (10, '7617 Twin Pines Plaza', 'Tafí del Valle', '9');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (50, '77 Starling Lane', 'Niquinohomo', '0');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (24, '8 1st Court', 'Akure', '6');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (34, '8 Ruskin Pass', 'Yeniköy', '0');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (40, '81 Pepper Wood Street', 'Heting', '8');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (39, '8169 Delaware Park', 'Chaloem Phra Kiat', '54648');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (41, '8364 Farragut Center', 'Canghou', '0');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (47, '8932 Linden Hill', 'Blobo', '08703');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (18, '9 Corscot Point', 'Övertorneå', '2');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (46, '90 Bowman Plaza', 'Konstantinovsk', '888');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (42, '93969 Ludington Avenue', 'Huanxi', '697');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (31, '96 Hanson Pass', 'Vila Nova', '257');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (30, '9673 Bluestem Point', 'Ngangpo', '2');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (6, '993 Luster Street', 'Urho', '8');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (2, 'Boleslavova 289', 'Liberec', '46006');
INSERT INTO symeprihlasky.address (id, street, city, postcode) VALUES (1, 'Dětský letní tábor', 'Černousy (Polní domky)', '46373');
